Repository ChicoState/PantryNode, pull requests merged in 2023-03, with the labels that each got.

#41 Add build action on push to main
  .github/workflows/actions.yml
Labels: DevOps

#44 Added Build Node Status Badge
  README.md
Labels: DevOps

#50 Add README instructions to run ESLint locally
  README.md
Labels: documentation, DevOps

#43 Docker containerisation of MVP
  .dockerignore
  Dockerfile
  README.md
  config/keys.js
  docker-compose.yml
Labels: DevOps

#74 Added Navigation and pages and components folder to start working on different pages.
  .eslintrc.cjs
  .gitignore
  PantryNodeReact/.gitignore
  PantryNodeReact/package-lock.json
  PantryNodeReact/package.json
  PantryNodeReact/src/App.tsx
  PantryNodeReact/src/Components/Layout.tsx
  PantryNodeReact/src/Components/Navigation/index.tsx
  PantryNodeReact/src/Components/Navigation/paths.tsx
  PantryNodeReact/src/Components/ProtectedRoute.tsx
  PantryNodeReact/src/index.css
  PantryNodeReact/src/index.tsx
  PantryNodeReact/src/pages/donor.tsx
  PantryNodeReact/src/pages/expiry.tsx
  PantryNodeReact/src/pages/index.tsx
  PantryNodeReact/src/pages/login.tsx
  PantryNodeReact/src/pages/sale.tsx
  PantryNodeReact/src/pages/stock.tsx
  PantryNodeReact/src/pages/summary.tsx
  PantryNodeReact/tsconfig.json
  README.md
  models/address.js
  models/aisle.js
  models/empl_info.js
  models/init-models.js
  models/permissions.js
  models/person.js
  models/section.js
  models/shelf.js
  models/shelf_contents.js
  models/site.js
  models/storage_type.js
  models/trans_items.js
  models/transaction.js
Labels: UI

#79 Routing and Navigation for React
  .eslintrc.cjs
  .gitignore
  PantryNodeReact/.gitignore
  PantryNodeReact/package-lock.json
  PantryNodeReact/package.json
  PantryNodeReact/src/App.tsx
  PantryNodeReact/src/Components/Layout.tsx
  PantryNodeReact/src/Components/Navigation/index.tsx
  PantryNodeReact/src/Components/Navigation/paths.tsx
  PantryNodeReact/src/Components/ProtectedRoute.tsx
  PantryNodeReact/src/index.css
  PantryNodeReact/src/index.tsx
  PantryNodeReact/src/pages/donor.tsx
  PantryNodeReact/src/pages/expiry.tsx
  PantryNodeReact/src/pages/index.tsx
  PantryNodeReact/src/pages/login.tsx
  PantryNodeReact/src/pages/sale.tsx
  PantryNodeReact/src/pages/stock.tsx
  PantryNodeReact/src/pages/summary.tsx
  PantryNodeReact/tsconfig.json
  README.md
Labels: feature, UI
