Repository ChicoState/PantryNode, pull requests merged in 2023-04, with the labels that each got.

#92 Sales Report View #78
  PantryNodeReact/src/Components/Layout.tsx
  PantryNodeReact/src/Components/Sale/SaleTable.tsx
  PantryNodeReact/src/pages/sale.tsx
Labels: feature, UI

#93 Form Validation on Login-Register View #89
  PantryNodeReact/src/pages/login.tsx
  PantryNodeReact/src/pages/register.tsx
Labels: UI

#99 Feed section home view #76
  PantryNodeReact/src/Components/Feed/Feed.tsx
  PantryNodeReact/src/Components/Layout.tsx
  PantryNodeReact/src/Components/Sale/SaleTable.tsx
  PantryNodeReact/src/pages/index.tsx
  PantryNodeReact/src/pages/sale.tsx
Labels: feature, UI

#115 Donor page improvements #77
  PantryNodeReact/src/pages/donor.tsx
  PantryNodeReact/src/pages/login.tsx
  PantryNodeReact/src/pages/register.tsx
  PantryNodeReact/src/pages/stock.tsx
  PantryNodeReact/src/redux-features/user.ts
Labels: UI

#142 Stock Summary Page
  PantryNodeReact/package-lock.json
  PantryNodeReact/package.json
  PantryNodeReact/src/Components/Summary/BarChart.tsx
  PantryNodeReact/src/pages/summary.tsx
Labels: feature, UI

#150 Linter error on frontend
  .github/workflows/actions.yml
  .github/workflows/linter.yml
  PantryNodeReact/.eslintrc.json
  PantryNodeReact/package.json
  PantryNodeReact/src/Components/Copyright.tsx
  PantryNodeReact/src/Components/Summary/BarChart.tsx
  PantryNodeReact/src/pages/donor.tsx
Labels: bug, UI

#132 QuaggaSKU Lookup Feature
  backend/.eslintrc.cjs
  backend/package-lock.json
  backend/package.json
  backend/sql/create_tables.sql
  backend/sql/dummy_data.sql
  backend/src/app.js
  backend/src/models/item.ts
  backend/src/routes/barcode.js
  backend/src/routes/index.js
  backend/src/views/index.ejs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Components/Navigation/paths.tsx
  frontend/src/Components/Quagga/scan.tsx
  frontend/src/pages/scanner.tsx
  frontend/tsconfig.json
Labels: feature

#122 Updated README.md file with latest technology stack
  README.md
Labels: documentation

#148 Added structure and example for backend API
  backend/src/app.js
  backend/src/routes/api/v1/employee.js
Labels: backend
